### PR TITLE
should support all methods, not properly tested

### PR DESCRIPTION
**Pull request by cretudorin**

### CODE REVIEW

**Comment by BlazeInferno64** [comment]
Thanks for pointing out the issue, I am working on the fix and adding some more functionality. Most probably by tomorrow it should get released!

**Comment by cretudorin** [comment]
btw, ideally you should setup a build system to minify everything. The easiest I know would  be bun.sh

**Comment by BlazeInferno64** [comment]
Alright @cretudorin would make sure about that, btw what other features you wanna see here?

**Comment by cretudorin** [comment]
Well, to be feature complete, so websockets, servers sent events and I'm not sure what else is missing

**Comment by BlazeInferno64** [comment]
@cretudorin Finally its been released, checkout the npm package from here
https://www.npmjs.com/package/blazed.js

 blazed.js@1.0.6

**Comment by BlazeInferno64** [comment]
@cretudorin New bug fixes and feature improvements have been released, checkout the npm package from here
https://www.npmjs.com/package/blazed.js

blazed.js@1.0.10

**Comment by BlazeInferno64** [comment]
@cretudorin can you try out the latest version of blazed.js?

Here's the updated package https://npmjs.com/package/blazed.js

**Pull request closed without merging**
